### ISSUE TITLE
Predictions on tcga sample data

### ISSUE THREAD

**Issue by MikeKlocCZ** [PaccMann/paccmann_predictor#20]
I am running locally the trained paccmann_predictor which I successfully downloaded according to guidelines. As well, I can run the example prediction on cell lines with their transcriptomic profiles stored at `data/gene_expression/gdsc-rnaseq_gene-expression.csv`. However, I don’t manage to run the predictions on any other datasets present in the downloaded folder `data/gene_expression`. In order to run, for example, the prediction on the samples from `tgct-tcga-rnaseq_gene-expression.csv` I just modified the path to the given RNA profile file and ran 

```
python paccmann_predictor/examples/IC50/test_paccmann.py \
splitted_data/gdsc_cell_line_ic50_test_fraction_0.1_id_997_seed_42.csv \
data/gene_expression/tgct-tcga-rnaseq_gene-expression.csv \
data/smiles/gdsc.smi \
data/2128_genes.pkl \
single_pytorch_model/smiles_language \
single_pytorch_model/weights/best_mse_paccmann_v2.pt \
results \
single_pytorch_model/model_params.json
```

This, however, does not work. The problem is apparently by the info line I get during the execution `INFO:test:Test dataset has 0 samples with 0 batches` which I believe is pointing to pytoda function `DrugSensitivityDataset` when assembling the data set. I get into the same troubles if I want to test my own data. Can you help me how to avoid this? Thanks!

**Comment by jannisborn** [comment]
Dear @MikeKlocCZ,

Thanks for the interest, indeed this is behavior is completely expected for  `gct-tcga-rnaseq_gene-expression.csv`. The TCGA data contains expression from human samples and there is no drug sensitivity values associated to them. In particular, if you feed this **together** with `gdsc_cell_line_ic50_test_fraction_0.1_id_997_seed_42.csv`, no samples are found.

For any training or inference you will always need three files:
- `smiles.smi` which contains two columns: the IDs of the drugs and their SMILES
- `expression.csv` which contains in the rows the cell IDs and in the columns the gene IDs
- `sensitivity.csv` which contains three columns, with cell IDs, drug IDs and sensitivity values (IC50)

We have these three files since it's the most efficient way of storing information. If you'd provide all in one CSV, the file would become very redundant due to the pairing. In your example, none of the cell IDs (from TCGA) can be matched to the gdsc IDs in the sensitvity data. Hence your dataset is empty. The code logic is written in such a way that entries (i.e., drug IDs or cell IDs) that cannot be matched are simply ignored. 

Note that the TCGA is not there to run drug sensitivty prediction. We used this to train a gene-expression VAE which then could be used for conditional de novo molecular generation, see this paper: https://www.cell.com/iscience/fulltext/S2589-0042(21)00237-6 This paper introduces PaccMannRL which builds upon PaccMann (the drug sensitivity prediction model you're interested in) for RL-based molecular generation.

If you run the code with `gdsc-rnaseq_gene-expression.csv` or `gdsc-rma_gene-expression.csv` it runs through because the pairs can be matched. If you want to adapt it, you have to adapt all three files in such a way that the IDs can be matched.

Hope this helps!
