### ISSUE TITLE
Access to trained affinity model and associated files

### ISSUE THREAD

**Issue by ashlin-k** [PaccMann/paccmann_predictor#22]
Hi! I'd like to use your pre-trained affinity model, but there doesn't seem to be any instructions on how to download this model, or associated files like the protein language file. Would you be able to direct me to these instructions, or add it to the README?

**Comment by jannisborn** [comment]
HI @ashlin-k ,

Thanks for the interest in our work. I recommend to check this repo: https://github.com/PaccMann/paccmann_kinase_binding_residues

and the two associated papers in JCIM. They both build upon the code in this repo and apply it to affinity prediction (focused on human kinases).
If you go through the repo, you will find instructions for how to run the model as well as a Box link to download a pretrained model.

Hope this helps! Otherwise please re-open or open a new issue :)

**Comment by ashlin-k** [comment]
Thanks so much for the quick reply! I was specifically looking for the model that was trained on BindingDB, as the protein target I'm interested in is not a kinase, and BindingDB covers a wider range of protein target types. Would you happen to have this model?

Could you also confirm that the where to find the "smiles_language.json" and "protein_language.pkl" files required for `predict_affinity.py`? Not sure if I can just use the `vocab.json` file [here](https://ibm.ent.box.com/s/xtml12cbd9bwb97odxykbl5qzzh147ml/folder/165871116183) for the smiles language file. I haven't been able to find the protein language one.
